server:
  port: 9111
  error:
    include-message: always
spring:
  application:
    name: dir-subs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: core
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:file:~/h2/testdb
    username: borisov
    password:
camel:
  springboot:
    main-run-controller:true
flow:
  tpk:
    enabled:true
file:
  name:
    work: /static/files/work/test.json
    data: two
    filePathPrepare: /home/hightmike/testFiles/
cron:
  scheduler: 0/9+*+*+*+*+?
logging:
  level:
    root: WARN
    ru.borisov: DEBUG

