server:
  port: 9111
  error:
    include-message: always
spring:
  application:
    name: dir-subs
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: core
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:file:~/h2/testdb
    username: borisov
    password:
  quartz:
    auto-startup: true
file:
  name:
    work: /static/files/work/test.json
    data: two
    filePathPrepare: /home/hightmike/testFiles/
scheduler:
  file:
    cron: '0/10+*+*+?+*+*+*'
logging:
  level:
    root: INFO
    ru.borisov: DEBUG
