server:
  port: 9111
  error:
    include-message: always
spring:
  application:
    name: dir-subs
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: user
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:file:~/h2/user_info
    username: borisov
    password:
  quartz:
    auto-startup: true
file:
  name:
    filePathPrepare: /home/hightmike/testFiles/
scheduler:
  file:
    cron: '0/10+*+*+?+*+*+*'
logging:
  level:
    root: INFO
    ru.borisov: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /home/hightmike/testFiles/log/userInfo.log
